//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AcunMedyaAkademiPortfolyo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblAbout
    {
        public int AboutId { get; set; }
        public string AboutFoto { get; set; }
        public string AboutTitle { get; set; }
        public string AboutTitle2 { get; set; }
        public string About1 { get; set; }
        public Nullable<System.DateTime> Birthday { get; set; }
        public string Website { get; set; }
        public string Phone { get; set; }
        public string City { get; set; }
        public Nullable<byte> Age { get; set; }
        public string Degree { get; set; }
        public string Email { get; set; }
        public string Freelance { get; set; }
        public string About2 { get; set; }
    }
}
