//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AcunMedyaAkademiPortfolyo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblStatistic
    {
        public int StatisticId { get; set; }
        public string StatisticTitle { get; set; }
        public Nullable<int> StatisticValue { get; set; }
        public string StatisticIcon { get; set; }
    }
}
